### ISSUE TITLE
UI Toolkit: Click on dropdown icon not open the dropdown selector

### ISSUE THREAD

**Issue by hungin** [TylerTemp/SaintsField#101]
It is irritating that clicking on the arrow of a dropdown is not workink.

**Comment by TylerTemp** [comment]
Hi,

Dropdown & AdvancedDropdown with array/list is already supported a while ago. 

```csharp
[Dropdown(nameof(GetDropdownItems))]
public float[] floats;

private DropdownList<float> GetDropdownItems()
{
    return new DropdownList<float>
    {
        { "1", 1.0f },
        { "2", 2.0f },
        { "3/1", 3.1f },
        { "3/2", 3.2f },
    };
}
```

![image](https://github.com/user-attachments/assets/8404adce-d3b8-43a1-9040-696cb94f9a02)

A price of code which might re-produce the issue, and you Unity version is appreciated. As Unity often broken on Serializable class/struct, or SerializedReference, or abstruct inherence, so this kind of information is important

**Comment by hungin** [comment]
It works well, what I mean is that you have to click in the field, if you click directly on the Arrow icon, dropdown will not open.
