### ISSUE TITLE
Regression: includeinctive no longer works

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#103]
repro: 
deactivate the parent of a bunch of renderers then add

```csharp
[GetComponentInChildren(includeInactive: false)]
public Renderer[] renderers;
```

all renderers including inactive will be added to the array

**Comment by TylerTemp** [comment]
Fixed in [3.6.0](https://github.com/TylerTemp/SaintsField/releases/tag/3.6.0)
