### ISSUE TITLE
`[Button]` fails when encounting 2 methods with the same name

### ISSUE THREAD

**Issue by AliAlbarrak** [TylerTemp/SaintsField#104]
Hello, I'm trying to add a `[Button]` to method that has a non-serializable parameter
```csharp
    [Button]
    public void AnimateUi(Action callback)
    {
        // ...
    }
```

I don't expect `Action` to be serialized in editor and I only need the `[Button]` for testing so I created and overload just for that.
```csharp
    [Button]
    public void AnimateUi() => AnimateUi(() => { });

    public void AnimateUi(Action callback)
    {
        // ...
    }
```

The button does not show if the new method name is the same name as the non-serializable one. I have to make it different for the button to show.

No errors or warnings are printed to the console.

```csharp
    [Button]
    public void AnimateUiTestHelper() => AnimateUi(() => { });
```

**Comment by TylerTemp** [comment]
Bug confirmed. A workaround before fixing, is to put ones with `[Button]` **UNDER** others.

**Comment by TylerTemp** [comment]
Closed cuz fixed
