### ISSUE TITLE
could be bug: getcomponent, serialized, hideininspector never fills the field

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#106]
with this
![image](https://github.com/user-attachments/assets/b8ecc8e7-d965-4622-953e-1c50e7691d52)
or that
![image](https://github.com/user-attachments/assets/7bed81d7-206f-4b12-8401-c91e38d0542a)
the field still doesn't get filled
![image](https://github.com/user-attachments/assets/792f93fc-23cd-467e-83a6-0bf2c16a5353)

**Comment by TylerTemp** [comment]
Duplicated of #75 

Unity's `HideInInspector` does not hide it, but remove it from inspector. Thus `GetComponent` can never work.

Use `ReadOnly` instead:

```csharp
[SerializeField, GetComponent, ReadOnly]
MCArmor _selfArmor;

// or
[GetComponent, ReadOnly]
public MCArmor _selfArmor;
```

![image](https://github.com/user-attachments/assets/8c06d718-a22a-42f9-9397-1ad53ff416e8)

**Comment by laurentopia** [comment]
gotcha, I'll do the readonly. thanks.
