### ISSUE TITLE
[Request] More ELayout.Horizontal options and Customizable backgrounds

### ISSUE THREAD

**Issue by dragon122** [TylerTemp/SaintsField#107]
1) Horizontal layout options
   One of the common uses for a Horizontal layout is drawing fields in a table-like fashion. 
   Currently there's no control over how horizontal fields placed and spaced.
![Unity_2024-11-27_10-28-35](https://github.com/user-attachments/assets/73690f20-bfbd-48d0-b1f5-0800249fd62e)

   In TriInspector there's [DeclareHorizontalGroup] that allows passing an array of field sizes:
![Unity_2024-11-27_09-50-10](https://github.com/user-attachments/assets/970cdf6a-3abb-4bf7-be4d-d25c06706c60)
   (Note the gradient field: with SaintsField it's squeezed into 1 pix)
   Having controls like this would be great.

2) Customizable background color of elements
  [GUIColor] is a very handy attribute in TriInspector allowing to color any element backgrounds (like in pic above). 

Again, amazing work has been done on this package, it's so close to perfection.

**Comment by TylerTemp** [comment]
Hi,

`GUIColor` has been added in [3.10.0](https://github.com/TylerTemp/SaintsField/releases/tag/3.10.0)

For everything about this issue, please see this list for a tracking progress

- [ ] Horizontal Layout
- [ ] GUIColor
    - [x] `GUIColor` for single field
    - [ ] `GUIColorStart` & `GUIColorEnd` for multiple fields
- [ ] Data Table for list/array of struct/class

**Comment by TylerTemp** [comment]
Hi,

Currently, the Horizental Layout has some issue if the label is on, and it indeed needs an option to set width of different fields.

However, if we're talking about null label situation, when I set it up the field didn't squeezed, but use shared space evenly (SaintsField 3.10.0).

```csharp
[Serializable]
public struct Info
{
    [LayoutStart("root", ELayout.Horizontal)]

    [RichLabel(null)] public Gradient gradient;
    [RichLabel(null)]
    public int i;
    [RichLabel(null)]
    public string thisIsALongDriveForPeopleWithNothingToThinkAbout;
}

[SaintsRow(inline: true), PlayaRichLabel("<color=pink><label/>")] public Info[] inputs;
```

I indeed adjusted how Layout organize field in UI Toolkit. Can you give a piece of code that the display is squeezed?

![image](https://github.com/user-attachments/assets/d3465f43-89ac-4b15-a1f1-26f0f2ecc646)

**Comment by dragon122** [comment]
Thanks, great work (and fast too!). No squeezing now, I think I've used "" in [RichLabel] instead of null in that example.
Can't (actually can - it's not urgent) wait for custom widths.

**Comment by TylerTemp** [comment]
Hi,

With [3.22.0](https://github.com/TylerTemp/SaintsField/releases/tag/3.22.0) we have `Table` which might be a better approach than `Layout` for a mini-table-like editor, which col hide & resize support.

Note it's a complex new feature so might contain bugs. Feel free to report if you face any.

```csharp
using SaintsField;

[Table]
public Scriptable[] scriptableArray;

[Serializable]
public struct MyStruct
{
    public int myInt;
    public string myString;
    public GameObject myObject;
}

[Table]
public MyStruct[] myStructs;
```

[![video](https://github.com/user-attachments/assets/82193a57-c051-4188-950d-9e7a9ee6e08d)](https://github.com/user-attachments/assets/1c574c0c-56e0-4912-8e00-49fb7e29d80c)
