### ISSUE TITLE
whats the usings?

### ISSUE THREAD

**Issue by JoyousSuccess** [TylerTemp/SaintsField#19]
whats the usings? namespaces?
to use   [Layout("GoRefs",ELayout.Foldout)]
i had to add 
using SaintsField.Playa;
?
i dont see usings in the docs... i always write it ontop on the margin on the title page docs when i print em out lol 
.. or youd put em by what needs what..

**Comment by TylerTemp** [comment]
Thanks for reporting.

normal attributes which are out-of-boxing usage, is under `using SaintsField;`

`SaintsEditor` components attributes are under `using SaintsField.Playa;`

This indeed is missing from the document. Will update the document (recently) on the next release. (And improve some other document descriptions)
