### ISSUE TITLE
EnumFlags incorrectly treats `HasFlag` as toggled on mixed bits

### ISSUE THREAD

**Issue by JoyousSuccess** [TylerTemp/SaintsField#20]
uh the EnumFlags thing doesnt work correctly as it should?
_(or am i wrong lol? ... think i had this code totally working in Odin.. odin annoying tho lol)_

i have this enum

	[Flags]
	public enum Bldg_DestructState {
		NONE = 0,
		TOP_LEFT = 1, TOP_RIGHT = 2,
		BOT_LEFT = 4, BOT_RIGHT = 8,
		ADJ_LEFT = 16, ADJ_RIGHT = 32,
		FOUR = TOP_LEFT | TOP_RIGHT | BOT_LEFT | BOT_RIGHT
	}

and your attribute thingy 
it will make the FOUR be an OR ... but its and AND...  right.. ?
also your on off replacing 0 ?

see this : https://giannisakritidis.com/blog/Enum-Flags-In-Unity/
![info](https://github.com/TylerTemp/SaintsField/assets/75836981/952f44d8-dde2-4e06-9181-3de5d1732864)

... when i select TOP_RIGHT  .. it also selects FOUR... 

![info2](https://github.com/TylerTemp/SaintsField/assets/75836981/1c10522e-3edd-4d10-b9b7-8a7221364304)

**Comment by JoyousSuccess** [comment]
yeah in normal unity drawer i pick TOP_RIGHT it only does TOP_RIGHT ... if i pick FOUR it picks my four i set up
![info3](https://github.com/TylerTemp/SaintsField/assets/75836981/7b6d9ebc-00a0-40b3-87c2-22c8afdce88b)
![info4](https://github.com/TylerTemp/SaintsField/assets/75836981/5c522010-d584-4108-be23-fdb73751985f)

**Comment by TylerTemp** [comment]
Confirmed. Yes, it's not correct. Thanks for reporting. Working on it.

**Comment by TylerTemp** [comment]
Please check if it's fixed in [3.0.1](https://github.com/TylerTemp/SaintsField/releases/tag/3.0.1)


https://github.com/TylerTemp/SaintsField/assets/6391063/6f5e3e57-85fb-44f2-ad5b-e269146b276c

**Comment by JoyousSuccess** [comment]
sry for delay.. seems to be fine now

**Comment by TylerTemp** [comment]
Closed as fixed
