### ISSUE TITLE
Support Indent for Layout

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#21]
Anything to give a common background and even indentation to a group of fields?

**Comment by TylerTemp** [comment]
A boxGroup function is mixed with layout. Ensure you enabled `SaintsEditor` before testing this example:


```csharp
using SaintsField.Playa;
using UnityEngine;

namespace SaintsField.Samples.Scripts.IssueAndTesting.Issue
{
    public class Issue21 : MonoBehaviour
    {
        public string beforeBox1;

        [Layout("The Lonesome Crowded West", ELayout.Background | ELayout.Title | ELayout.TitleOut)]
        public string s1;
        [Layout("The Lonesome Crowded West")]
        public string s2;

        public string afterBox1;

        [SepTitle(EColor.Gray)]

        public string beforeBox2;

        [Layout("Strangers to Ourselves", ELayout.Background | ELayout.Title | ELayout.TitleOut | ELayout.Foldout)]
        public string s3;
        [Layout("Strangers to Ourselves")]
        public string s4;

        public string afterBox2;
    }
}
```

![image](https://github.com/TylerTemp/SaintsField/assets/6391063/a29de590-ef17-4962-b2e1-00bf0430a880)

------------------------------

For indentation it's not supported yet. Do you mean indent horizontal (like Unity's indent) or vertical (like Unity's `[Space]`)? I might add it if it's a reasonable request (and not too complex)

**Comment by laurentopia** [comment]
> Ensure you enabled `SaintsEditor`
 I think I did 
![image](https://github.com/TylerTemp/SaintsField/assets/26075468/fb5df47a-2f2f-4755-9e40-ddc7c9312f16)
but the ELayout enum is out of reach
![image](https://github.com/TylerTemp/SaintsField/assets/26075468/15c3c914-0c2f-41ec-9671-77662f2a5ca4)

**Comment by laurentopia** [comment]
Fantastic!
Thanks.
