### ISSUE TITLE
UI Toolkit prevent CustomPropertyDrawer of generic subclass from being used

### ISSUE THREAD

**Issue by ACCIAI0** [TylerTemp/SaintsField#23]
If I use either `ShowIf` or `HideIf` attribute on a field or property with a Type with a custom property drawer, that field is rendered in the inspector with a default PropertyField instead of using the custom drawer. For Example:

![immagine](https://github.com/TylerTemp/SaintsField/assets/29255588/f6ca434c-04c8-48b4-9ec8-91a206695cc8)

This is how it looks like with the `HideIf` attribute,

![immagine](https://github.com/TylerTemp/SaintsField/assets/29255588/815d42a2-690a-4bfb-a840-96dc3ffea660)

This is how it should be using the custom drawer (it only shows the internal list of entries)

**Comment by TylerTemp** [comment]
... Wait... I sort of having some idea...

**Comment by ACCIAI0** [comment]
@TylerTemp The fact is I AM using UIElements. the only difference between my code and your example is that the custom editor is technically assigned to the abstract parent type of the one I serialize in my screenshot, with `editorOfChildClasses = true`

**Comment by TylerTemp** [comment]
@ACCIAI0  Do you mean:

```csharp
[Serializable]
public abstract class SuperSource
{

}

[Serializable]
public class Source: SuperSource
{
    [SerializeField] private string[] serializedEntries;
}

// public Source normal;
[HideIf(nameof(toggle)), InfoBox("Type CustomDrawer fallback", above: true)] public Source withIf;
```

with drawer:

```csharp
[CustomPropertyDrawer(typeof(ImGuiFallback.SuperSource))]  // super class of the data
public class SourceDrawer : PropertyDrawer
{
    #region IMGUI

    public override float GetPropertyHeight(SerializedProperty property, GUIContent label)
    {
        SerializedProperty arrProperty = property.FindPropertyRelative("serializedEntries");
        return EditorGUI.GetPropertyHeight(arrProperty, label, true);
    }

    public override void OnGUI(Rect position, SerializedProperty property, GUIContent label)
    {
        SerializedProperty arrProperty = property.FindPropertyRelative("serializedEntries");
        EditorGUI.PropertyField(position, arrProperty, label, true);
    }
    #endregion

#if UNITY_2021_3_OR_NEWER
    public override VisualElement CreatePropertyGUI(SerializedProperty property)
    {
        SerializedProperty arrProperty = property.FindPropertyRelative("serializedEntries");
        return new PropertyField(arrProperty, property.displayName);
    }
#endif
}
```

I still can not re-produce it on Unity 2022.2.0f1 under UI Toolkit. Please share more information, like your Unity version, and a simple drawer that has this issue

**Comment by ACCIAI0** [comment]
I'm using it in Unity 2022.3.20f1, but I'm unsere it makes any difference. The bare-bones skeleton of my code is as follows:

```csharp
[Serializable]
public class Container<T1, T2>
{
    [Serializable]
    protected sealed class Entry
    {
        public T1 Name;
        public T2 Object;
    }

    [SerializeField]
    protected List<Entry> Entries;
}

[Serializable]
public sealed class ContainerChild<T> : Container<string, T>
{
    public T GetByName(string name)
    {
        var entry = Entries.Find(e => e.Name == name);
        return entry == default ? default : entry.Object;
    }
}
```

**Comment by TylerTemp** [comment]
Bug confirmed

**Comment by TylerTemp** [comment]
Hi @ACCIAI0 

Please check if it's fixed in [3.0.6](https://github.com/TylerTemp/SaintsField/releases/tag/3.0.6)

given the code you provide with:

```csharp
public bool toggle;

public GameObjectChild normal;
[HideIf(nameof(toggle)), InfoBox("Inherent Fallback", above: true)] public GameObjectChild inherent;
// won't work on old Unity
[HideIf(nameof(toggle)), InfoBox("Direct Fallback", above: true)] public ContainerChild<GameObject> direct;
```

gives:

![image](https://github.com/TylerTemp/SaintsField/assets/6391063/5bdf5eaa-89d9-4734-b9ed-595e38ac1c10)

**Comment by TylerTemp** [comment]
This issue is closed cuz it's fixed.

If you still have a problem with this issue, please comment here and I'll open this issue again.

**Comment by ACCIAI0** [comment]
Sorry, I had a lot of stuff to do and this slipped my mind. I tried it out and can confirm it works like a charm. Nice job, your speed at addressing issues make this library very valuable to me!
