### ISSUE TITLE
LayerAttribute not retaining value after change

### ISSUE THREAD

**Issue by ACCIAI0** [TylerTemp/SaintsField#28]
If I set a value to a int field with the LayerAttribute assigned it looks fine until i close the inspector, at that point it's value is lost, it's value going back to Default.

**Comment by TylerTemp** [comment]
Hi @ACCIAI0 

Please check if it's fixed in [3.0.9](https://github.com/TylerTemp/SaintsField/releases/tag/3.0.9)

**Comment by TylerTemp** [comment]
This issue is now closed cuz it's been fixed.

Please comment below if you still face this issue and I'll open it again.
