### ISSUE TITLE
is there a way to GetComponent in self and parent?

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#41]
Because this 
![image](https://github.com/TylerTemp/SaintsField/assets/26075468/355a907c-f199-4dd6-b1bc-0ee61c561729)
is causing that
![image](https://github.com/TylerTemp/SaintsField/assets/26075468/3edab656-35fe-4e8a-8112-f23732eea1c7)

**Comment by TylerTemp** [comment]
Hi,

seems like `MCUnit` is not a Monobehavior.

Here is what I tested on Unity 2022.2 with UI Toolkit:

```csharp
// MCUnit.cs
public class MCUnit : MonoBehaviour
{
}

// Issue41GetComp.cs
public class Issue41GetComp : MonoBehaviour
{
    [GetComponent] [GetComponentInParent] public MCUnit mcUnit;
}
```

Example of geting it from self:

![image](https://github.com/TylerTemp/SaintsField/assets/6391063/d161aa4a-11b9-4c34-9323-5dac83f43f33)

from parent:

![image](https://github.com/TylerTemp/SaintsField/assets/6391063/5e565999-8fd2-4143-90b2-09f5886eff8b)


Can you give a small example of how `MCUnit` look like?

**Comment by laurentopia** [comment]
It's solved and ... I don't remember what I did 🗡️ 
Here is MCUnit


```using UnityEngine;
using System.Collections.Generic;
using SaintsField;
using SaintsField.Playa;
using Panda;
using UnityEngine.AI;
using Vertx.Debugging;
using Gizmos = UnityEngine.Gizmos;
using Random = UnityEngine.Random;
#if UNITY_EDITOR
#endif

#pragma warning disable 0649
public enum Team { ENEMY = 0, PLAYER = 1 }
public class MCUnit : MonoBehaviour
{
	[GetComponent]
	public MCAttackSelector attackSelector;
	[GetComponent]
	public AnimationController anim;
	public float detectionRange = 100;
	public int score = 0,
						threat = 1;
	public Team team = Team.ENEMY;
	public LayerMask enemyLayer,
									friendLayer;
	public bool noPanda;
	[SepTitle(EColor.Violet)]
	[SerializeField]
	float health = 10.0f;```
