### ISSUE TITLE
GetComponent etc need better error handling and report

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#42]
I'm getting this error and no idea what caused that. 
I must have added an attribute that's not compatible with something and it breaks Saints.
Do you have an idea?
![image](https://github.com/TylerTemp/SaintsField/assets/26075468/46a7831c-857d-4b63-ad72-12bf418bf1a1)
![image](https://github.com/TylerTemp/SaintsField/assets/26075468/a2ac224e-c35b-491d-b6d0-d4f9e5ffd5fd)

**Comment by laurentopia** [comment]
this is the component that, when expanded, causes this error.
I used to have 
[GetComponentInParent]
[GetComponent]
public MCUnit unit;
![image](https://github.com/TylerTemp/SaintsField/assets/26075468/f5d2d745-98cc-41a3-81eb-ecacc263d65e)

**Comment by laurentopia** [comment]
never mind... i had deleted a field reference to a component then forgot to remove [GetComponent]
is it possible to spit out clear error messages?

**Comment by TylerTemp** [comment]
> never mind... i had deleted a field reference to a component then forgot to remove [GetComponent] is it possible to spit out clear error messages?

Certainly. The `GetComponent*` utils are implemented in quite a short time so do not have a clearer error message (except `GetComponentByPath`, which handled many error cases already)

**Comment by laurentopia** [comment]
You're the best!!
