### ISSUE TITLE
[GetComponentInPanret] doesn't work when in prefab edit (2020.3.48)

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#43]
[GetComponent] works fine, tho
![image](https://github.com/TylerTemp/SaintsField/assets/26075468/17c8d9b9-544e-42f8-9953-fe707e938234)
![image](https://github.com/TylerTemp/SaintsField/assets/26075468/c9e57a01-c961-40e0-b112-be17a93bfc30)
![image](https://github.com/TylerTemp/SaintsField/assets/26075468/cebc4b0b-9ec4-4fd8-bee2-516f0ee76170)

**Comment by TylerTemp** [comment]
Hi,

Can you check if you mean `GetComponentInParents` than `GetComponentInParent`?

For what I tested:

```csharp
public class Issue43 : MonoBehaviour
{
    [GetComponentInParent] public MCUnit mcUnit;
}
```

Ensure I'm in prefab editing mode:

![image](https://github.com/TylerTemp/SaintsField/assets/6391063/13b528e2-0059-406e-aa60-5ce784b70805)

Attach `MCUnit` to `PR_lankyman`

![image](https://github.com/TylerTemp/SaintsField/assets/6391063/d85f4ce5-085c-4568-8dec-1427a4e5fbb8)

Then attach `Issue43` to it's directly children:

![image](https://github.com/TylerTemp/SaintsField/assets/6391063/0d8338eb-eea9-4f5a-8312-92cb0f7ce6c6)

Both `lankyman` (a normal GameObject) and `lankyman (1)` (a prefab) works as expected

![image](https://github.com/TylerTemp/SaintsField/assets/6391063/41e270d9-e7a3-4458-b167-74c7e0b65968)

So maybe your `MCUnit` is not direct parent of your `GetComponentInParent`, thus you need `GetComponentInParents`

If not, please tell me where your `GetComponentInParent` attached in your screenshot so I can try re-produce this issue.

**Comment by laurentopia** [comment]
I think it was problem with HotReload breaking things again. It works as expected now, but sometimes not due to HR intercepting stuff.
