### ISSUE TITLE
pick a component of interface?

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#46]
Is this possible?
![image](https://github.com/TylerTemp/SaintsField/assets/26075468/a9ab8d95-9111-4ab2-ae26-bb76e50841d2)
![image](https://github.com/TylerTemp/SaintsField/assets/26075468/709340cb-d9ce-4551-9c2b-68eb2ae26e7c)
I'm getting that
![image](https://github.com/TylerTemp/SaintsField/assets/26075468/6aeb7a37-5672-45c6-a3d6-2b8f8da574a2)

**Comment by TylerTemp** [comment]
Hi,

Correct me if I'm wrong: `SerializeReference` does not work with a pure `Interface`.

A way to do it is `SaintsInterface`. See related document for more information.

```csharp
public class MCPhysicsRelay: MonoBehaviour
{
    public SaintsInterface<UnityEngine.Object, IPhysicsReceiver> receiver1;
    
    // For old Unity, use this instead
    [Serializable]
    public class PhysicsReceiverInterface : SaintsInterface<UnityEngine.Object, IPhysicsReceiver> { }
    public PhysicsReceiverInterface receiver2;
    
    // this also works with the GetComponent* decorators
    [GetComponentInChildren] public PhysicsReceiverInterface receiver3;
    
    // at this point it does not work with `RequireType` but I'm working on it

    private void Awake()
    {
        Debug.Log(receiver3.I);  // get the actual interface
    }
}
```

![image](https://github.com/TylerTemp/SaintsField/assets/6391063/3bb5c572-aabb-4c34-8918-b19fa3ef48f0)

**Comment by TylerTemp** [comment]
Hi, this issue is closed as answered. If you still have related issue, please comment below and I'll open it again
