### ISSUE TITLE
is there an option to have 	[MinMaxSlider(0, 20)] expand range if the user input a larger/smaller value?

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#48]
combining the convenience of the minmax slider with the flexibility of a vector2 :)

**Comment by laurentopia** [comment]
awesome

**Comment by TylerTemp** [comment]
Hi,

this feature has been added in [3.4.4](https://github.com/TylerTemp/SaintsField/releases/tag/3.4.4), please have a try (and hope it has no bug.

```csharp
[MinMaxSlider(0, 10, free: true)] public Vector2 myRange;
```

**Comment by TylerTemp** [comment]
This issue is now closed as it's been implemented. Comment below if you still have similar issues and I'll open it again
