### ISSUE TITLE
when use [showif] not work on array

### ISSUE THREAD

**Issue by ZeroUltra** [TylerTemp/SaintsField#5]
Hi !!!
code like this:
```
public class NewMonoBehaviour : MonoBehaviour
{
    public bool useTargetIds;
    [ShowIf(nameof(useTargetIds))]
    public int[] targetIds;

    public TestAllowClass linkgo;

    [System.Serializable]
    public class TestAllowClass
    {
        public bool useTargetIds;
        [ShowIf(nameof(useTargetIds))]
        public int[] targetIds;
    }
}
```
![image](https://github.com/TylerTemp/SaintsField/assets/38253805/de71265c-9426-4d1f-99b1-303057fd26aa)

**Comment by ZeroUltra** [comment]
Unity2021.3.33 Unity2022.3.16

**Comment by TylerTemp** [comment]
Thanks for reporting.

This is because:

> Directly using on list/array will apply to every direct element of the list, this is a limit from Unity.

The solution is to write one attribute for `SaintsEditor`.

This will be implemented in the future. But please note, `SaintsEditor` is not a core value of this project (it just works), so it‘s low priority and might take some time (versions) to see this happens.

**Comment by ZeroUltra** [comment]
Thank you for your reply. I look forward to this feature.

**Comment by ZeroUltra** [comment]
If someone desperately needs it, I have another plan, though not perfect.
1. 
```
[System.Serializable]
public class NestedArray<T>
{
    public T[] Array;
}
```
2.
```
using System;
using UnityEngine;
#if UNITY_EDITOR
using UnityEditor;
#endif

[AttributeUsage(AttributeTargets.Field, Inherited = true)]
public class HideNestedArrayAttribute : PropertyAttribute
{

}
#if UNITY_EDITOR
[CustomPropertyDrawer(typeof(HideNestedArrayAttribute))]
public class HideNestedArrayDrawer : PropertyDrawer
{
    public override void OnGUI(Rect position, SerializedProperty property, GUIContent label)
    {
        var array = property.FindPropertyRelative("Array");
        EditorGUI.PropertyField(position, array, new GUIContent(property.displayName));
    }
    public override float GetPropertyHeight(SerializedProperty property, GUIContent label)
    {
        var array = property.FindPropertyRelative("Array");
        // These numbers are tried out. I don't know how to get it.
        if (array.isExpanded)
        {
            return 70 + Mathf.Clamp((array.arraySize-1) * 20, 0, float.MaxValue);
        }
        else
            return 20;
    }
}
#endif
```
ok, test it
```
using UnityEngine;
using SaintsField;

public class NewMonoBehaviour : MonoBehaviour
{
    public bool useIds;
    [ShowIf("useIds"), HideNestedArray]
    public NestedArray<int> ids;

    public TestArray testArray;
    public TestArray[] testArrays;

    [System.Serializable]
    public class TestArray
    {
        public bool useIds;
        [ShowIf("useIds"), HideNestedArray]
        public NestedArray<int> ids;
    }
}

```
![image](https://github.com/TylerTemp/SaintsField/assets/38253805/119e3702-4b10-4902-913f-62917d327fc2)

**Comment by TylerTemp** [comment]
Please update 2.1.12 to use `PlayaShowIf`/`PlayaHideIf` for array. Note: you need to enable `SaintsEditor` to make it work. See [Set Up SaintsEditor](https://github.com/TylerTemp/SaintsField/tree/2.1.12?tab=readme-ov-file#set-up-saintseditor) in document. And note:

> Please note, any Editor level component can not work together with each other (it will not cause trouble, but only one will actually work). Which means, OdinInspector, NaughtyAttributes, MarkupAttributes, SaintsEditor can not work together.

If the attributes have any errors, please open a new issue )))
