### ISSUE TITLE
Examples work, once in a new script, doesn't work

### ISSUE THREAD

**Issue by KamilTheDev** [TylerTemp/SaintsField#51]
All the examples work fine, but once I try in my own script, Layout Group doesn't work. Unity 2022.3.27f1

![Screenshot 2024-07-14 194814](https://github.com/user-attachments/assets/649cf5f2-bc5b-4444-9b69-ea44dff50236)

`LayoutGroupExample.cs`:
```cs
using SaintsField.Playa;

namespace SaintsField.Samples.Scripts.SaintsEditor
{
    public class LayoutGroupExample : SaintsMonoBehavior
    {
        [SepTitle("Break By End", EColor.Gray)]
        // end group
        public string beforeGroup;

        [LayoutGroup("Group", ELayout.Background | ELayout.TitleOut)]
        public string group1;
        public string group2;  // starts from this will be automatically grouped into "Group"
        public string group3;

        [LayoutEnd("Group")]  // this will end the "Group"
        public string afterGroup;

        [SepTitle("Break By Group", EColor.Gray)]

        // break group
        public string breakBefore;

        [LayoutGroup("break", ELayout.Background | ELayout.TitleOut)]
        public string breakGroup1;
        public string breakGroup2;

        // this group will stop the grouping of "break"
        [LayoutGroup("breakIn", ELayout.Background | ELayout.TitleOut)]
        public string breakIn1;
        public string breakIn2;

        [LayoutGroup("break")]  // this will be grouped into "break", and also end the "breakIn" group
        public string breakGroup3;
        public string breakGroup4;

        [LayoutEnd("break")]  // end, it will not be grouped
        public string breakAfter;

        [SepTitle("Break By Last Group", EColor.Gray)]
        public string beforeGroupLast;

        [LayoutGroup("GroupLast")]
        public string groupLast1;
        public string groupLast2;
        public string groupLast3;
        [Layout("GroupLast", ELayout.Background | ELayout.TitleOut)]  // close this group, but be included
        public string groupLast4;

        public string afterGroupLast;
    }
}
```

```TestMonoScript.cs``` (copied from above example):
```cs
using SaintsField;
using SaintsField.Playa;
using UnityEngine;

public class TestMonoScript : MonoBehaviour
{
    [SepTitle("Break By End", EColor.Gray)]
    // end group
    public string beforeGroup;

    [LayoutGroup("Group", ELayout.Background | ELayout.TitleOut)]
    public string group1;
    public string group2;  // starts from this will be automatically grouped into "Group"
    public string group3;

    [LayoutEnd("Group")]  // this will end the "Group"
    public string afterGroup;

    [SepTitle("Break By Group", EColor.Gray)]

    // break group
    public string breakBefore;

    [LayoutGroup("break", ELayout.Background | ELayout.TitleOut)]
    public string breakGroup1;
    public string breakGroup2;

    // this group will stop the grouping of "break"
    [LayoutGroup("breakIn", ELayout.Background | ELayout.TitleOut)]
    public string breakIn1;
    public string breakIn2;

    [LayoutGroup("break")]  // this will be grouped into "break", and also end the "breakIn" group
    public string breakGroup3;
    public string breakGroup4;

    [LayoutEnd("break")]  // end, it will not be grouped
    public string breakAfter;

    [SepTitle("Break By Last Group", EColor.Gray)]
    public string beforeGroupLast;

    [LayoutGroup("GroupLast")]
    public string groupLast1;
    public string groupLast2;
    public string groupLast3;
    [Layout("GroupLast", ELayout.Background | ELayout.TitleOut)]  // close this group, but be included
    public string groupLast4;

    public string afterGroupLast;
}
```

**Comment by TylerTemp** [comment]
Hi

Layout need SaintsEditor enabled, which is not enabled by default to avoid conflict.

The most easy way is Window - Saints - Apply SaintsEditor.  For more information about config please check the related document

**Comment by KamilTheDev** [comment]
I have indeed already pressed Apply SaintsEditor before creating the issue.
![image](https://github.com/user-attachments/assets/93b55e5f-e504-4d09-b925-0cf158fbe7d5)

In my post, you can see adding the pre-provided example script works fine, but copy & pasting it into my own script has the Layout Element not working.

**Comment by TylerTemp** [comment]
OK, understood.

In this case, I'm afraid that your project has a script that also highjack the `UnityEditor.Editor`, which has a higher priority than other 3rd-party plugins.

A very easy way to verify that:

First, under any `Editor` folder, create the following script:

```csharp
using SaintsField.Editor;

[CanEditMultipleObjects]
[CustomEditor(typeof(TestMonoScript), true)]
public class ApplySaintsEditor : SaintsEditor
{
}
```

If it works now, that means there are scripts that override `CustomEditor` which is way too high priority. If it does not work, then sorry buddy there is indeed some problem with your project that I can not think of.

If this script works, there is a (very annoying) way to find out which hijake it:

```csharp
foreach (Assembly asb in AppDomain.CurrentDomain.GetAssemblies())
{
    Type[] allTypes = asb.GetTypes();
    List<Type> allEditors = allTypes
        .Where(type => type.IsSubclassOf(typeof(UnityEditor.Editor)))
        .ToList();

    foreach (Type eachEditorType in allEditors)
    {
        foreach (CustomEditor customEditor in eachEditorType.GetCustomAttributes<CustomEditor>(true))
        {
            var v = typeof(CustomEditor)
                .GetField("m_InspectedType",
                    BindingFlags.Instance | BindingFlags.Static | BindingFlags.NonPublic |
                    BindingFlags.Public | BindingFlags.DeclaredOnly | BindingFlags.FlattenHierarchy)
                ?.GetValue(customEditor);
            Debug.Log($"Found editor: {eachEditorType} -> {customEditor}: {v}");
        }
    }
}
```

It'll print all the editor for it's corresponding types. Carefully check overrides like `UnityEngine.Object`, `MonoBehavior`, `Component`, which should be the one that blocked other inspectors.

**Comment by KamilTheDev** [comment]
Thank you, the first and last script did restore the correct functionality.

From the debug script, I found this:
`Found editor: ExternalPropertyAttributes.Editor.ExternalCustomInspector -> UnityEditor.CustomEditor: UnityEngine.Object`

This is from [Quibli](https://assetstore.unity.com/packages/vfx/quibli-anime-shaders-and-tools-203178), a toon shader asset. I imported Quibli into a new project and confirmed that is the cause of the issue.

I need to keep Quibli and its editor tools in my project, as I'm using it. Is it okay to just continuing to use the last script you provided to avoid having to make modifications to Quibli asset?

**Comment by TylerTemp** [comment]
Yes. because most of the time, we only need to deal with MonoBehavior and ScriptableObject. The `Component` type only comes into handy when you inherent, for example, `Button`, `SpriteRenderer` etc, which is usually not the case. MonoBehavior & ScriptableObject should cover most of the game development. And you can always add `CustomEditor` manually when the target type is not included.
