### ISSUE TITLE
How to insert `[Space]` right before `[LayoutGroup]` starts?

### ISSUE THREAD

**Issue by KamilTheDev** [TylerTemp/SaintsField#52]
If I have the following code:
```cs
public Image maskImage;
[ReadOnly] public float initialScale;

[Space(100f)]

[LayoutGroup("Animation", ELayout.Background | ELayout.TitleOut)]
public float duration = 1f;
public Ease easeIn;
public Ease easeOut;
[LayoutEnd("Animation")]
```
I get the result:
![Screenshot 2024-07-14 230107](https://github.com/user-attachments/assets/23f97616-9ea6-408f-9663-afad906ef9f8)

How can I make the space appear outside of the `[LayoutGroup]`?

**Comment by TylerTemp** [comment]
At this point, no.

I am plaining to add some space for `Layout` to increase some readability, and also #44 will also allow to set space below a field, so please stay tuned.

**Comment by TylerTemp** [comment]
Hi,

Though not directly related, the [3.1.5](https://github.com/TylerTemp/SaintsField/releases/tag/3.1.5) now add 2px space for Layout to improve some readability which might make the situation a bit better.

**Comment by TylerTemp** [comment]
Hi @KamilTheDev , please try [version 3.2.1](https://github.com/TylerTemp/SaintsField/releases/tag/3.2.1) for this feature.

![image](https://github.com/user-attachments/assets/3fd148ed-41fa-45d4-9354-f5b198e8d072)

```csharp
public string start;

[LayoutGroup("Group", ELayout.FoldoutBox, marginTop: 10, marginBottom: 10)]
public string group1;
public string group2;
public string group3;
[LayoutEnd("Group")]

public string middle;

[Layout("Layout", ELayout.TitleBox, marginTop: 10, marginBottom: 10)] public string layout1;
[Layout("Layout")] public string layout2;
[Layout("Layout")] public string layout3;

public string end;

[Serializable]
public struct MyStruct
{
    public string start;

    [LayoutGroup("Group", ELayout.FoldoutBox, marginTop: 10, marginBottom: 10)]
    public string group1;
    public string group2;
    public string group3;
    [LayoutEnd("Group")]

    public string middle;

    [Layout("Layout", ELayout.TitleBox, marginTop: 10, marginBottom: 10)] public string layout1;
    [Layout("Layout")] public string layout2;
    [Layout("Layout")] public string layout3;

    public string end;
}

[SaintsRow] public MyStruct myStruct;
```

**Comment by TylerTemp** [comment]
This issue is now closed as it's been implemented. If you still face similar issue, comment below and I'll open it again.
