### ISSUE TITLE
is there a way to ShowInInspector + Progressbar?

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#53]
![image](https://github.com/user-attachments/assets/9bada99c-92d7-46c9-b341-3793ea7c3a54)
This properly shows the field in gray but doesn't display the progressbar.

**Comment by TylerTemp** [comment]
Hi,

a non-serialized field is not supported by serialized property decorator, yet.

The fix order is:

1.  Bug fix in the issue list
2.  The features that already added in the milestone
3.  Support richLabel for non-serialized field
4.  Support more type for non-serialized field
5.  Support custom drawer for non-serialized field <--- it's here (

So please stay tuned )

**Comment by laurentopia** [comment]
Thanks, and as always, your attributes are the best!
