### ISSUE TITLE
`[Button]` Function to find and assign references to prefab doesn't save?

### ISSUE THREAD

**Issue by KamilTheDev** [TylerTemp/SaintsField#54]
If I have this code:
```cs
[SerializeField] private RectTransform rectTransform;
[SerializeField] private TMP_Text message;

[Button]
private void GetRefs()
{
    rectTransform = transform.GetComponent<RectTransform>();

    message = transform.Find("Message").GetComponent<TMP_Text>();
}
```

Clicking the button assigns fields correctly, but they're never actually saved to the prefab. If you exit and go back into the prefab, the fields are empty.

Edit: If I make some change manually, then it will save properly. Is there some function I can call to force Unity to save the prefab?

**Comment by KamilTheDev** [comment]
Calling `EditorUtility.SetDirty(gameObject); ` seems to be the correct way to mark prefab as modified.

**Comment by TylerTemp** [comment]
> Calling `EditorUtility.SetDirty(gameObject); ` seems to be the correct way to mark prefab as modified.

Yes, but it's more recommended to use `Undo.RecordObject(gameObject, name)`  before you make a change so you can undo it.
