### ISSUE TITLE
Is there an attribute to show the content of a dictionary?

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#57]
And while we're here, tuples?

**Comment by TylerTemp** [comment]
Show a dictionary, not yet. `ShowInInspector` will have this feature in a very near future release I guess, cus I need this function for my game project too...

**Comment by TylerTemp** [comment]
Hi @laurentopia ,

this feature has been added in [3.2.0](https://github.com/TylerTemp/SaintsField/releases/tag/3.2.0). This version has some breaking changes, please read the change log before upgrading.

**Comment by laurentopia** [comment]
Damn! You're on fire!
