### ISSUE TITLE
3.20 bug: [GetComponentInParent] no longer works

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#58]
I thought it was a base vs derived thing but when i switched to the derived class I saw that it didn't work at all
![image](https://github.com/user-attachments/assets/5e340689-348f-43ee-8178-c531b6abff5e)
![image](https://github.com/user-attachments/assets/52532752-6e21-4e55-893c-ee25a68ad073)
and when I set it by hand:
![image](https://github.com/user-attachments/assets/bace7590-fa65-4cbc-8a0a-f71922a37212)
so i verified the version number: 
![image](https://github.com/user-attachments/assets/2c7bd268-6f20-442f-9194-6a31afaf5c40)

**Comment by laurentopia** [comment]
GetComponentInChildren works tho

**Comment by laurentopia** [comment]
and [Required works] so the bug seems to be of parcouring the hierarchy upwards

**Comment by TylerTemp** [comment]
Hi,

Sorry it's not well documented: `GetComponentInParent`, is different from Unity's build-in one.

Try GetComponentInParent**s** instead

**Comment by laurentopia** [comment]
ohhhhh i get it! thanks :D

**Comment by laurentopia** [comment]
I recommend this instead to avoid confusion (keep both for legacy)
