### ISSUE TITLE
GetComponentInParents/Children still shows error box when assigned

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#59]
I think it's by design but it is not very useful to still show an error when the object was deparented and therefore the references component is no longer in the same hierarchy
![image](https://github.com/user-attachments/assets/3a774474-f02f-4123-ace3-7b055f1b1c32)

**Comment by TylerTemp** [comment]
Hummmm, so you mean, the MCUnityRelay can be used in different situations, in some case the Unit is in parents, some are not. 

And if it's not, and when it's been manually assigned, the error message looks redundant, do I understand correctly?

**Comment by TylerTemp** [comment]
Well, `GetComponentByPath` has argument which uses `EGetComp.ForceResign | EGetComp.NoResignButton` to achive this feature. This is not implemented on other `GetComponent*` yet.

I think I might do this when I have some spare time

**Comment by laurentopia** [comment]
> And if it's not, and when it's been manually assigned, the error message looks redundant, do I understand correctly?

that's right. since the attributes are used as a helper, not a nanny, the error message is overreaching.

**Comment by TylerTemp** [comment]
Hi,

this is now possible in [3.4.0](https://github.com/TylerTemp/SaintsField/releases/tag/3.4.0):

```csharp
[GetComponentInParents] public SpriteRenderer notInParents;
[GetComponentInChildren] public SpriteRenderer notInChildren;

// no button at all
[GetComponentInParents(EXP.Silent | EXP.NoPicker | EXP.NoResignButton)] public SpriteRenderer notInParentsNoButton;
[GetComponentInChildren(EXP.Silent | EXP.NoPicker | EXP.NoResignButton)] public SpriteRenderer notInChildrenNoButton;
```

![image](https://github.com/user-attachments/assets/f002c7b7-8e1e-4fdf-a37a-98d1850dbd12)

The config is kinda tedious. It might be optimized on a later version.

Note: This update might contain bugs.

**Comment by laurentopia** [comment]
amazing! thanks
