### ISSUE TITLE
nested group possible?

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#65]
I'd like to have "death" grouped inside "damage" group, is this possible? it seems to only split the group.
![image](https://github.com/user-attachments/assets/35b04946-ce32-46b9-b165-363709240870)
![image](https://github.com/user-attachments/assets/50fa9117-e5f7-4e62-9e89-165212495627)

**Comment by TylerTemp** [comment]
Yes but note the appearance looks different in IMGUI and UI Toolkit:

```csharp
[LayoutGroup("Damage", ELayout.FoldoutBox)]
public string damage1;
public string damage2;

[LayoutGroup("Damage/Death", ELayout.FoldoutBox)]
public string death1;
public string death2;
[LayoutEnd("Damage/Death")]

[LayoutGroup("Damage", ELayout.FoldoutBox)]  // there is some issue: the Layout need to be announced again...
public string damage3;
public string damage4;

[LayoutEnd("Damage")]
public string otherField;
```


UI Toolkit:

![image](https://github.com/user-attachments/assets/e23fbb05-ecee-40e4-87fe-070b4db0bc2a)


IMGUI:

![image](https://github.com/user-attachments/assets/4062847f-50c3-4199-9c48-64ca6c050b49)

**Comment by laurentopia** [comment]
Gotcha, so A/B is the format and A needs to be re announced after A/B was ended. 
Thanks.

Curious: why are the foldout arrows to the right in UIT?

**Comment by laurentopia** [comment]
also is there a way to indent an array so its arrow doesn't get confused with the group? 
![image](https://github.com/user-attachments/assets/7b8bc45e-49b7-418c-8cce-05599392afa6)

**Comment by TylerTemp** [comment]
> Yes but note the appearance looks different in IMGUI and UI Toolkit:



The new version [3.2.6](https://github.com/TylerTemp/SaintsField/releases/tag/3.2.6) supports the following sytax now:

```csharp
[LayoutGroup("Damage", ELayout.FoldoutBox)]
public string damage1;
public string damage2;

[LayoutGroup("./Death", ELayout.FoldoutBox)]
public string death1;
public string death2;
[LayoutEnd(".")]

public string damage3;
public string damage4;

[LayoutEnd]  // close all
public string otherField;
```

IMGUI:

![image](https://github.com/user-attachments/assets/202fef37-2ffc-478c-8737-4e5f4a2e50e1)


UI Toolkit:

![image](https://github.com/user-attachments/assets/fc5a369d-ef69-469c-ad17-2c66304002d2)

**Comment by laurentopia** [comment]
very cool, but regression https://github.com/TylerTemp/SaintsField/issues/76

**Comment by laurentopia** [comment]
in light mode, arrow remains white
![image](https://github.com/user-attachments/assets/b07c392c-3bd2-4453-adb9-094d9522e4fa)

**Comment by TylerTemp** [comment]
> in light mode, arrow remains white 

Unfortunately, color multiple for image in IMGUI is quite a pain... SaintsField has a utility to change the color, but this issue will be a low-priority one, as it requires more work to do, including dispose the colored image in a proper time.
