### ISSUE TITLE
[GetComponentInChildren] on a list shows list count to 1 instead of 2 (regression?)

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#70]
repro:
add a dummy script to both children, let's call it... Dummy.cs
add a parent script FindDummy.cs
[GetComponentInChildren]
public List<Dummy> dummies;
it will only finds the first dummy, this used to work
![image](https://github.com/user-attachments/assets/e0117843-84d2-4fa5-90e0-f1ded9846b46)
then when i open the list in the inspector it finds both
![image](https://github.com/user-attachments/assets/c13114a8-0f5c-4ec7-82c8-b153ae5d8dfd)

**Comment by TylerTemp** [comment]
This function is, well, poorly implemented yet.

The reason of this is, array/list relies on `SaintsEditor` to fill some value, and only the array/list expanded, the drawer can be drawn, which is the actual filling code can work. Well, at least in IMGUI (UI Toolkit expand it by default) it is this case.

This feature will be implemented later I guess. I'm taking a short vacation aparting from my work & stuff, so will be after that.

**Comment by laurentopia** [comment]
awesome!
I'll just keep an eye out for funky populating until then
