### ISSUE TITLE
is there an attrib that changes the name of element into a chosen field?

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#74]
For example this:
![image](https://github.com/user-attachments/assets/0a020ac7-d854-4f4c-ab30-51079ae4869f)
where elements 0 is replaced by "Acknowledge" as if I were to use a string instead of enum.
I tried this workaround but it won't fool Unity :D
![image](https://github.com/user-attachments/assets/0b23b9d2-fa87-481f-ab7b-3d0c5e61aa7d)

**Comment by TylerTemp** [comment]
Yes

```csharp
[Serializable]
public enum ANIMSTATE
{
    None,
    State,
    AnotherState,
}

[Serializable]
public struct AudioStateClips
{
    public ANIMSTATE state;
}

[RichLabel(nameof(LabelAudioStateClips), true)]
public AudioStateClips[] audioClips;

public string LabelAudioStateClips(AudioStateClips clip, int index)
{
    return $"{clip.state} ({index})";
}
```

![image](https://github.com/user-attachments/assets/35ba1bda-85a9-4df9-89b9-8b2a08d3f86c)

**Comment by laurentopia** [comment]
wow nice! thanks!
