### ISSUE TITLE
[Required] regression in 3.2.6

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#76]
prefab required even with a prefab referenced
![image](https://github.com/user-attachments/assets/7c5a1b62-8a2b-4a3e-a7e5-30136ad75e5a)
![image](https://github.com/user-attachments/assets/791229d0-e937-4488-ac82-066eb21c495a)

**Comment by TylerTemp** [comment]
Hi,

Again I can not re-produce it. More information is required to locate this issue (

Im using the simple code:

```csharp
public class Issue79 : SaintsMonoBehaviour
{
    [Serializable]
    public struct MyStruct
    {
        [Required] public Issue79 prefab;
    }

    [SaintsRow] public MyStruct myStruct;

    [Required] public Issue79 prefab;
}
```

But it works fine under 2022.2.0f1, both IMGUI and UI Toolkit, both in scene mode and perfab editing mode.

(P.S. to attach an video you can just drag and drop the file in the comment area)

https://github.com/user-attachments/assets/8073687d-17e6-42f8-adf0-0aa270a5cbd8

**Comment by laurentopia** [comment]
like by magic, it solved itself.
must be hot reload...
