### ISSUE TITLE
potential bug: a field to a scriptableobject with [Expandable]/[GetScriptableObject] lost its reference to that SO

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#78]
It happened after I upgraded to latest saintsfields so it could be a problem

**Comment by TylerTemp** [comment]
This might not be a problem of expandable, but `GetScriptableObject`, well, which at least happened to my project.

Kinda difficult to locate what caused it though, need some time to figure it out

**Comment by TylerTemp** [comment]
This issue might be because of a value comparison bug which has been fixed in [3.4.0](https://github.com/TylerTemp/SaintsField/releases/tag/3.4.0)

I'll leave this issue open for another month. If no problem found then I'll close it as fixed. (But if the issue still occurs, I'll open it again)

**Comment by TylerTemp** [comment]
Update about this issue:

if the target is a prefab but the prefab is put directly inside a scene, the value will be lost.

**Comment by laurentopia** [comment]
Ah ok that's a problem. I think it's how Unity handles reference. Could you maybe add a warning in such conditions? To help prevent hard to find errors.

**Comment by TylerTemp** [comment]
> Ah ok that's a problem. I think it's how Unity handles reference. Could you maybe add a warning in such conditions? To help prevent hard to find errors.

Sorry for the misleading... When I post that reply I indeed find a bug that makes it not working on prefab.

That bug has been fixed, but not quite sure it's that bug that lead all this. So this issue is still pending. I need some more time to investigate on it.

**Comment by TylerTemp** [comment]
Hi,

[3.4.9](https://github.com/TylerTemp/SaintsField/releases/tag/3.4.9) fixes a bug which related to `[Expandable]` in IMGUI, that a `SerializedObject` did not get cached and lead to problem.

This issue might be related to that.

Please upgrade to 3.4.9 to check if the bug is gone.

Thanks

**Comment by laurentopia** [comment]
Thank you.
