### ISSUE TITLE
[showif],[playashowif]... not work Class inheritance

### ISSUE THREAD

**Issue by ZeroUltra** [TylerTemp/SaintsField#8]
**me again 2!
Unity2022.3.16**
```
public class TestBase : MonoBehaviour
{
    public bool haveInfo;
    [PlayaShowIf(nameof(haveInfo))]public string infoTextureName;

    public bool isInt;
    [ShowIf(nameof(isInt))] public int intA;
}
public class Test : TestBase
{
    [Space(20)]
    public bool isString;
    [ShowIf("isString")]
    public string strA;

    public bool haveInfo2;
    [PlayaShowIf(nameof(haveInfo2))] public string infoTextureName2;
}
```
![image](https://github.com/TylerTemp/SaintsField/assets/38253805/0cad041e-8762-4f61-bc37-13f432e24e2d)

**Comment by TylerTemp** [comment]
Hi, please upgrade to "2.2.0" to see if it's fixed.

![image](https://github.com/TylerTemp/SaintsField/assets/6391063/034f452c-8129-4fd8-bed1-0d43a65d1fbf)


![image](https://github.com/TylerTemp/SaintsField/assets/6391063/efee02a3-a797-4cda-9ac6-5ac8ccf0f8f5)
