### ISSUE TITLE
Restrict Enum-Flags to singular entry? 

### ISSUE THREAD

**Issue by ModischFabrications** [TylerTemp/SaintsField#81]
First off. great utility, I am just starting out but I like it so far. Now my problem: 

I am building a system where modules have one specific value of a `ModuleType` and sockets accept a subset of them. What I need is a method to get the full range (default behaviour) of "[Flags]" on sockets while still keeping modules restricted to just one singular entry (default for non-flag enums). 

[This link](https://localjoost.github.io/Making-only-one-entry-of-a-Flag-Enum-selectable-in-the-Unity-Editor/) seems to do a very similar thing, but I would obviously like to have it integrated into SaintsField directly. I thought this way actually implemented because of the "AllowMultiple" description, but I now understand that's related to the attribute, not the field. 

Not important, I can enforce it via validation for now, but I think it would be a good fit for this utility. Thanks!

**Comment by ModischFabrications** [comment]
For reference, this is my workaround: 

```
    public class Module : MonoBehaviour
    {
        [Flags]
        public enum Type
        {
            None = 0,
            Primary = 1,
            Secondary = 1 << 1,
            Optics = 1 << 2,
            Props = 1 << 3,
            Utility = 1 << 4,
        }

        public Type type;

        private void OnValidate()
        {
            Assert.IsTrue(type.HasSingular(), $"{name} needs exactly one type");
        }
    }

// ...

    public static class EnumExtensions
    {
        public static bool HasSingular(this Enum e)
        {
            return math.ispow2(Convert.ToInt32(e));
        }
    }
```

**Comment by TylerTemp** [comment]
This will be a good feature. I need it too.

As I'm working on some features/bug fixes, this feature will be implemented later, and will be put into the next milestone.

To track the working progress of this project, see [Milestone#06](https://github.com/TylerTemp/SaintsField/milestone/6)

**Comment by TylerTemp** [comment]
Hi,

This feature has been added to [3.4.8](https://github.com/TylerTemp/SaintsField/releases/tag/3.4.8). Just add a `Dropdown` or `AdvanceDropdown` on your enum field, and it'll work as expected, no matter the enum is `Flags` or not.

```csharp
[Serializable, Flags]
public enum MyEnum
{
    [RichLabel("1")]  // RichLabel is optional. Just for you to have more fancy control 
    First,
    [RichLabel("2")]
    Second,
    [RichLabel("3")]
    Third,
    [RichLabel("4/0")]
    ForthZero,
    [RichLabel("4/1")]
    ForthOne,
}

[Dropdown] public MyEnum myEnumDropdown;
[AdvancedDropdown] public MyEnum myEnumAdvancedDropdown;
```

![image](https://github.com/user-attachments/assets/46ddc541-8773-4571-9aeb-f3fe25c5f783)

![image](https://github.com/user-attachments/assets/ebc2e2f7-3534-4ff7-8710-29a990f5dea4)
