### ISSUE TITLE
Layouts doesn't work

### ISSUE THREAD

**Issue by GariestGary** [TylerTemp/SaintsField#84]
Hi! I'm trying to make tabs layout, but seems like it doesn't work, i copied exactly code snippet you mentioned in documentation
![image](https://github.com/user-attachments/assets/57ed6bc3-59ec-4cd2-96c5-c9ba629e3812)
but in editor nothing happens
![image](https://github.com/user-attachments/assets/c560acaa-d44d-43d1-a719-a89d1478dcb8)
i'm using assembly definition and adding today.comes.saintsfield.Runtime as reference. Even if i moving script out of asmdef folder it doesn't work too
Maybe i'm missed something

Thanks in advance!

**Comment by TylerTemp** [comment]
Hi,

1.  Ensure you [have `SaintsEditor` enabled](https://github.com/TylerTemp/SaintsField?tab=readme-ov-file#setup-saintseditor).
2.  If still not working, there might be another plugin that has higher priority overriding `UnityEditor.Editor`, see [this comment](https://github.com/TylerTemp/SaintsField/issues/51#issuecomment-2227303081) to have a basic debugging

If it sitll not working, I'll need to know your Unity version, and the way you enable `SaintsEditor` in your project ), and a output of your `CustomEditor` (You might use [pastebin](https://pastebin.com/) for the large output)

**Comment by GariestGary** [comment]
You're a wizard! It works now! 
Btw, are you planning to make site with structured documentation (like github pages with mkdocs or something)
Because it is easy to lost a bunch of important information in this endless readme file
If no then i will be happy to help doing this for you

**Comment by TylerTemp** [comment]
> are you planning to make site with structured documentation

As a lot of things [still pending to be done](https://github.com/TylerTemp/SaintsField/milestone/6), plus some improvements in plan, well, at least I won't do it in a short time. It'll be much much later...

>  If no then i will be happy to help doing this for you

Yeah sure, that'll be nice. Well, if it's github pages I guess for new version I can sync new/changed content with PR. I never tried online service before so not sure how things can be updated. But anyway, I'm not really worried about the choice :)

If so I'll add a link in README to that site.

**Comment by TylerTemp** [comment]
This issue is closed as solved. If you still have issue about this, please comment below and I'll re-open it.

**Comment by TylerTemp** [comment]
> You're a wizard! I enabled SaintEditor and it works now! Btw, are you planning to make site with structured documentation (like github pages with mkdocs or something)? Because it is easy to lost a bunch of important information in this endless readme file If no then i will be happy to help doing this for you

Hi, it's now there:

> [!TIP]
> A better document with TOC & Search: [saintsfield.comes.today](https://saintsfield.comes.today/)
