### ISSUE TITLE
Searchable `[ReferencePicker]`

### ISSUE THREAD

**Issue by braide** [TylerTemp/SaintsField#87]
Would be nice to be able to search for a type with `[ReferencePicker]`, convenient if the search bar could be auto focused so you can start typing after clicking the dropdown button

**Comment by TylerTemp** [comment]
Well, let's agree that most dropdown attributes are better with `AdvancedDropdown` 😃 

When I write most of the attributes, I haven't implement the `AdvancedDropdown` yet. So yeah, why not. This should be not hard so might be seen soon.

**Comment by TylerTemp** [comment]
Hi, this feature has been added in [3.3.7](https://github.com/TylerTemp/SaintsField/releases/tag/3.3.7)

**Comment by TylerTemp** [comment]
Hi,

This issue is now closed as it's been fixed. If you still face the same (or similar) issue, please comment below and I'll open it again.
