### ISSUE TITLE
Is there a way to pick an interface in the inspector?

### ISSUE THREAD

**Issue by laurentopia** [TylerTemp/SaintsField#88]
if I do
```csharp
public interface IPhysicsRelayReceiver
{
	 void OnTriggerEnterRelayed(Collider other);
	 void RegisterCollider(Collider col);
}
//relays attacking capsule, used by melee
public class MCPhysicsRelay : MonoBehaviour
{
	[SerializeReference]
	[RequireType(typeof(IPhysicsRelayReceiver))]
	public IPhysicsRelayReceiver receiver;
}
```

it doesn't display the drop bucket like other reference fields do, only a button.
![image](https://github.com/user-attachments/assets/94cde864-a861-49c6-b342-ddd407ec55e0)
Could you add a drag and drop area?

**Comment by laurentopia** [comment]
it's possible that it's a bug...
![image](https://github.com/user-attachments/assets/5c25fc9d-28b8-4318-bf57-48cab96fbfe9)

**Comment by TylerTemp** [comment]
Hi,

AFAIK, an interface should either be non-UnityEngine.Object, or a UnityEngine.Object. they use two different mechanisms: 
1.  The first one uses `SerializeReference` provided by Unity (which can not be used on a UnityEngine.Object), 
2.  while the latter uses c#'s default serializetion process.

I don't know if there is a way to make the two use the same process. At this point, we can only do:

```csharp
public interface IPhysicsRelayReceiver
{
    void OnTriggerEnterRelayed(Collider other);
    void RegisterCollider(Collider col);
}

public struct ExampleStructOfInterface : IPhysicsRelayReceiver
{
    public string DisplayName;

    public void OnTriggerEnterRelayed(Collider other)
    {
    }

    public void RegisterCollider(Collider col)
    {
    }
}

public class MCPhysicsRelay : MonoBehaviour, IPhysicsRelayReceiver
{

    // example of non-UnityEngine.Object
    [SerializeReference, ReferencePicker]
    public IPhysicsRelayReceiver nonUnityObject;

    // example of UnityEngine.Object
    public SaintsInterface<UnityEngine.Object, IPhysicsRelayReceiver> unityObject;

    public void OnTriggerEnterRelayed(Collider other)
    {
    }

    public void RegisterCollider(Collider col)
    {
    }
}
```

![image](https://github.com/user-attachments/assets/3d3cf479-b1c8-4c09-9523-c88e76776637)

**Comment by laurentopia** [comment]
SaintsInterface seems to be the easiest to use with minor changes and more importantly it doesn't break when changing the class name like [SerializeReference] does.
I'll use that, or a few hidden vars.
Thanks.
