### ISSUE TITLE
OnValueChangedAttribute 在 IMGUI 下不会生效

### ISSUE THREAD

**Issue by Lx34r** [TylerTemp/SaintsField#90]
`OnValueChangedAttributeDrawer.OnPropertyEndImGui `的前置判断需要`onGUIPayload.changed`，但是`SaintsPropertyDrawer.OnGUI`从未对此赋值，就不单独提pr了。

![image](https://github.com/user-attachments/assets/02af65bf-cc06-4fed-afb4-0cc0930150e2)
![image](https://github.com/user-attachments/assets/66c5117b-3928-4511-b377-c44d3b19844d)

**Comment by TylerTemp** [comment]
... 应该是 `if (error == "")`...

应该是某次重构`Util.GetValue`时写飞了。项目越来越大，我的工作环境主要在 UI Toolkit，有些IMGUI的BUG还真一下发现不了（所以当初为毛要写两套…只能怪Unity的IMGUI无法兼容UI Toolkit了…）

我提一下…感谢指出，不然这个BUG要好久才会被发现。

**Comment by TylerTemp** [comment]
感谢支持，已更新到 [3.4.2](https://github.com/TylerTemp/SaintsField/releases/tag/3.4.2)

**Comment by Lx34r** [comment]
我也主要使用`UITK`，正好今天写编辑器脚本省事只重写了`OnInspectorGUI`，发现`OnGUI`居然没触发`OnValueChanged`回调...
`UITK`下`的SaintsField`用起来是真的好用，hack做自定义样式修改也方便，感谢~
