### ISSUE TITLE
UI Toolkit 下，OnValueChangedAttribute 与 RangeAttribute 组合会导致无法触发回调

### ISSUE THREAD

**Issue by Lx34r** [TylerTemp/SaintsField#91]
**UI Toolkit** 下，Unity内置的`RangeAttribute `会将原属性绘制成**Slider**/**SliderInt** element，导致无法正常回调。

**[case]**
![image](https://github.com/user-attachments/assets/b339d048-501e-4254-9803-2697a30f0f6d)

**Comment by TylerTemp** [comment]
实际上这是一个 Known Issue, 把 SaintsField 的属性放到第一位就行了： [文档](https://github.com/TylerTemp/SaintsField/?tab=readme-ov-file#order-matters)

> However, Unity only allows decorators to be loaded from top to bottom, left to right. Any drawer that does not properly handle the fallback will override PropertyDrawer follows by. Thus, ensure SaintsField is always the first decorator.

所以这样就行了:

```csharp
[OnValueChanged(nameof(Changed)), Range(1, 5)]  // SaintsField 会处理 Fallback 到其它装饰器
public int dir;

private void Changed()
{
    Debug.Log($"changed={dir}");
}
```

PropertyDrawer 默认没有 fallback 系统（PropertyField做的fallback，但问题一大堆，我已经处理了里面的大量问题…）

当然如果有 SaintsEditor 其实可以处理这个问题的，但是这个的优先级就没那么高了。另外就是现在的文档太tedious了…有个QA板块也会好很多…

总之…这个问题目前可以绕过，更好的方案，后面再说吧…

**Comment by Lx34r** [comment]
抱歉，我没注意到readme中的pitfalls。
确实如此，目前文档太过于冗长，查阅定位只能ctrl + f，很难注意到底部的注意事项，有个QA或者Wiki确实会更好。
