### ISSUE TITLE
[BUG] `[Dropdown]` does not support `long` type?

### ISSUE THREAD

**Issue by braide** [TylerTemp/SaintsField#92]
I get `InvalidCastException` when I use a `long` type for the `Dropdown` attribute. The exception gets thrown from `SaintsField/Editor/Utils/Util.cs:159` and I guess its because a `long` gets the propertyType value `SerializedPropertyType.Integer`. So if you add a check to see if its a `long` and use the `property.longValue` instead it works.
Kind of like this from line 153 in `Util.cs`
```
case SerializedPropertyType.LayerMask:
case SerializedPropertyType.Integer:
case SerializedPropertyType.Enum:
    if (newValue is long)
        property.longValue = (long) newValue;
    else
        property.intValue = (int) newValue;
```

**Comment by TylerTemp** [comment]
Hi, can you give:

1.  your `SaintsField` version
2.  your Unity version
3.  possible a piece of code to re-produce

For what im testing:

1.  SaintsField 3.4.5
2.  Unity 2022.3.14f1

```csharp
[Dropdown(nameof(LongValues))] public long longValue;

public DropdownList<long> LongValues() => new DropdownList<long>
{
    { "1", 1L },
    { "2", 2L },
    {"max", long.MaxValue},
    {"min", long.MinValue},
};
```

works fine

![image](https://github.com/user-attachments/assets/e9c063b4-2479-4623-9ceb-1524950624b3)

**Comment by braide** [comment]
Hello,

1. I used 3.4.2 but updated to 3.4.5, but the error is still there.
2. Unity 6000.0.24f1, 2022.3.40f1 
3. The code you provided also gives the error.

It seems to work (selects the correct value) but it still gives the exception. I tried Unity 2022.3.40f1 as well with the code you provided and also get the exception there.

**Comment by TylerTemp** [comment]
Bug confirmed. For the unity's internal code, the `intValue` actually uses `long`, so I guess change the cast to `long` will just work fine.

**Comment by TylerTemp** [comment]
Hi,

This bug has been fixed in [3.4.6](https://github.com/TylerTemp/SaintsField/releases/tag/3.4.6), please have a look~

**Comment by braide** [comment]
Hey,

Works in 3.4.6, Thank you!

**Comment by TylerTemp** [comment]
Hi, 3.4.6 contains critical bugs, please upgrade [3.4.7](https://github.com/TylerTemp/SaintsField/releases/tag/3.4.7) instead...
